
-- Insert all completed tasks into Done column
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'academic calendar and key dates', 'Academic calendar and key dates management', 'medium', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/educationoffice/ErYt4tl1AxFAgqaGQvXXjRYBOxJZ7bo3wa516Xxqbee32w?e=OqRDR0', 0, '2025-10-01 05:38:39'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'American Service, Baloon, exam paper, Medal inpo, paper temp a5 - a4', 'Design materials for American Service and related items', 'medium', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EpfUNEiTdjNLp8KJxt1Bwf0Be7_f54PlTSN0wQdYAIDorw?e=UTCmiT', 1, '2025-10-01 05:50:49'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Wezary Champions Campaign in Stirling Schools', 'Wezary Champions Campaign design and materials', 'medium', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/ElJ4tMYIxnRDt6rfB6z9-dABZrLjX1mMcjXvuz3Xsu_3AA?e=lnl9ok', 2, '2025-10-01 07:14:53'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'rise mewlid nabi program', 'Rise mewlid nabi program video content', 'medium', 'Video/Photo', 'Stirling Schools', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1252524983345424', 3, '2025-10-01 12:08:30'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik secondary soyınlanması cience etkinliği', 'Ishik secondary science activity video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/3547805645361509', 4, '2025-10-01 12:10:14'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik secondary öğrenci toplantı', 'Ishik secondary student meeting coverage', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1211581561002053&set=pcb.1211582687668607', 5, '2025-10-01 12:11:33'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'slemani primary 1 librarry', 'Slemani primary 1 library video content', 'medium', 'Video/Photo', 'Slemani', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1325469629375087', 6, '2025-10-01 12:13:08'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'us girls highi school veli toplantı', 'US girls high school parent meeting coverage', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=785334694128038&set=pcb.785335440794630', 7, '2025-10-01 12:16:54'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'bagdad ana okul', 'Baghdad kindergarten video content', 'high', 'Video/Photo', 'Baghdad', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/EjHSp0GHiipKijeHHlQRCwQBhAoV6gMXmytJhpwZH4KSQw?e=HoLvhZ', 8, '2025-10-05 06:37:28'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'soran video montaj', 'Soran video editing and production', 'medium', 'Video/Photo', 'Slemani', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/EqlBZNCfXXZKhdQY1W3NvNoB-qmKQPkwjafse1CUBmvMew?e=SgG5lL', 9, '2025-10-05 06:38:09');

-- Insert more completed tasks (continuing the sequence)
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'kral gunu icin video loop', 'King Day video loop creation', 'high', 'Video/Photo', 'Stirling Schools', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/En6jpP8CnfRAgZpvOK9DOwMBxbfNVhTQbz9dFTQd9LuGLw?e=N11hXe', 10, '2025-10-05 06:39:04'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'suleymaniye foto cekim', 'Sulaymaniyah photo shooting', 'medium', 'Video/Photo', 'Slemani', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/EgPkDhEhxzBOgMP4JW5JkssBBB5LUhjVQFD8E8eCLiJ5Nw?e=Mqub61', 11, '2025-10-05 06:40:00'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Translation Day (Facebook)', 'Social media post for International Translation Day on Facebook', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.facebook.com/523543736455941/posts/1224688573008117', 12, '2025-10-05 06:53:52'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Translation Day (Instagram)', 'Social media post for International Translation Day on Instagram', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/p/DPN6FbjEabq/', 13, '2025-10-05 06:54:11'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Translation Day (Linkedin)', 'Social media post for International Translation Day on LinkedIn', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://linkedin.com/feed/update/urn:li:share:7378685847912599552', 14, '2025-10-05 06:54:30'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Translation Day (Twitter)', 'Social media post for International Translation Day on Twitter', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1972920063146578125', 15, '2025-10-05 06:54:54'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Kirkuk (Facebook)', 'Back to school campaign for Kirkuk on Facebook', 'medium', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://facebook.com/523543736455941/posts/1224949872981987', 16, '2025-10-05 06:59:18'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Kirkuk (Instagram)', 'Back to school campaign for Kirkuk on Instagram', 'medium', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/p/DPOjdmhER_w/', 17, '2025-10-05 06:59:34'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Kirkuk (Linkedin)', 'Back to school campaign for Kirkuk on LinkedIn', 'medium', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://linkedin.com/feed/update/urn:li:ugcPost:7378776962020040704', 18, '2025-10-05 06:59:54'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Kirkuk (Twitter)', 'Back to school campaign for Kirkuk on Twitter', 'medium', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1973011607396438229', 19, '2025-10-05 07:00:09');

-- Insert more completed tasks
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Basra (Facebook)', 'Back to school campaign for Basra on Facebook', 'high', 'Social Media', 'Basra', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://facebook.com/523543736455941/posts/1609839959979988', 20, '2025-10-05 08:44:01'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Basra (Instagram)', 'Back to school campaign for Basra on Instagram', 'high', 'Social Media', 'Basra', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/reel/DPO0mujj09g/', 21, '2025-10-05 08:44:17'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Basra (Twitter)', 'Back to school campaign for Basra on Twitter', 'high', 'Social Media', 'Basra', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1973048157605863763', 22, '2025-10-05 08:44:53'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Basra (YouTube)', 'Back to school campaign for Basra on YouTube', 'high', 'Social Media', 'Basra', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.youtube.com/watch?v=XbPycs3ROJg', 23, '2025-10-05 08:46:02'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Back To School Basra (TikTok)', 'Back to school campaign for Basra on TikTok', 'high', 'Social Media', 'Basra', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.tiktok.com/@stirlingschools/video/7555906285275712780', 24, '2025-10-05 08:46:35'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Visit of CEO Mr. Green to Kirkuk (Facebook)', 'CEO visit coverage for Facebook', 'high', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://facebook.com/523543736455941/posts/1225672659576375', 25, '2025-10-05 10:15:11'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Visit of CEO Mr. Green to Kirkuk (Instagram)', 'CEO visit coverage for Instagram', 'high', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/p/DPQl4GoEX8a/', 26, '2025-10-05 10:15:39'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Visit of CEO Mr. Green to Kirkuk (Linkedin)', 'CEO visit coverage for LinkedIn', 'high', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://linkedin.com/feed/update/urn:li:ugcPost:7379063701192097792', 27, '2025-10-05 10:16:10'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Visit of CEO Mr. Green to Kirkuk (Twitter)', 'CEO visit coverage for Twitter', 'high', 'Social Media', 'Kirkuk', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1973298344140079295', 28, '2025-10-05 10:16:28'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Day of Older Persons (Facebook)', 'International Day of Older Persons social media post', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://facebook.com/523543736455941/posts/1225754882901486', 29, '2025-10-05 10:20:18');

-- Insert more tasks (continuing with the pattern)
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Day of Older Persons (Instagram)', 'International Day of Older Persons Instagram post', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/p/DPQzwozEUkt/', 30, '2025-10-05 10:20:35'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Day of Older Persons (Linkedin)', 'International Day of Older Persons LinkedIn post', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://linkedin.com/feed/update/urn:li:share:7379094151759335424', 31, '2025-10-05 10:20:51'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'International Day of Older Persons (Twitter)', 'International Day of Older Persons Twitter post', 'medium', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1973328381199482946', 32, '2025-10-05 10:21:06'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Wezary Award and Honoring Ceremony (Instagram)', 'Wezary Award ceremony Instagram coverage', 'medium', 'Social Media', 'Slemani', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/p/DPTqi63kayN/', 33, '2025-10-05 10:24:43'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Wezary Award and Honoring Ceremony Slemani (Facebook)', 'Wezary Award ceremony Facebook post', 'medium', 'Social Media', 'Slemani', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://facebook.com/523543736455941/posts/1226760696134238', 34, '2025-10-05 10:25:06'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Wezary Award and Honoring Ceremony Slemani (Linkedin)', 'Wezary Award ceremony LinkedIn post', 'medium', 'Social Media', 'Slemani', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://linkedin.com/feed/update/urn:li:ugcPost:7379496023037014016', 35, '2025-10-05 10:25:27'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Wezary Award and Honoring Ceremony Slemani (Twitter)', 'Wezary Award ceremony Twitter post', 'medium', 'Social Media', 'Slemani', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1973730613799669928', 36, '2025-10-05 10:25:47'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'World Teachers Day (Facebook)', 'World Teachers Day Facebook celebration post', 'high', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://facebook.com/523543736455941/posts/1229210962555878', 37, '2025-10-05 10:29:31'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'World Teachers Day (Instagram)', 'World Teachers Day Instagram celebration post', 'high', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://www.instagram.com/p/DParGfSEdlj/', 38, '2025-10-05 10:31:02'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'World Teachers Day (Linkedin)', 'World Teachers Day LinkedIn celebration post', 'high', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://linkedin.com/feed/update/urn:li:share:7380482488453734400', 39, '2025-10-05 10:31:48');

-- Insert design tasks
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'World Teachers Day (Twitter)', 'World Teachers Day Twitter celebration post', 'high', 'Social Media', 'Stirling Schools', 'Mohammed', 'mohammed.yousif@stirlingschools.co.uk', 'https://twitter.com/a/status/1974716722608226351', 40, '2025-10-05 10:33:36'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), '3 years old came to school_US_social media', '3 years old enrollment social media design', 'medium', 'Design', 'Erbil', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EoDOYJ5892ZMqb3vv5S4abgBgMlWfTkt-v2nzMKvRLDtUw?e=LPogQd', 41, '2025-10-06 08:42:02'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), '3 years old came to school_US_RollUP', '3 years old enrollment rollup design', 'medium', 'Design', 'Erbil', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EosgjnvEdlxIo2DRvgK7FAsBO6aVvAvPV1EtYMw6yPJ6cg?e=gKg1k0', 42, '2025-10-06 08:42:19'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'After-School Clubs Announcement', 'After-school clubs announcement materials', 'medium', 'Update/Technical', 'Stirling Schools', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ei4p8vZuzixOoHhfShVELacBLgB4AARWYmqls1EWhN2jSw?e=qvFbd0', 43, '2025-10-06 08:42:45'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'STUDENT & PARENT CALENDAR Ishik Boys High School', 'Student and parent calendar for Ishik Boys High School', 'high', 'Update/Technical', 'Erbil', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:b:/s/MarketingTEAM/EWJOKYSFRXNMo-bGmxSOKawBj0jzyBkiYd0YXMwhk5umFQ?e=them5x', 44, '2025-10-06 08:44:08'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'STUDENT & PARENT CALENDAR Nilufer schools', 'Student and parent calendar for Nilufer schools', 'high', 'Update/Technical', 'Erbil', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:b:/s/MarketingTEAM/Ec6vVe4IVMRIs7e-zCeDnEcBvudwUCBlMp8ks5b3x02MVA?e=pSS8cL', 45, '2025-10-06 08:48:20'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Page Homework chart -students-A2-baghdad', 'Homework chart design for Baghdad students', 'medium', 'Design', 'Baghdad', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:b:/s/MarketingTEAM/EW-Nzd4DJ45OtK0Bxe9B8VYB4uCWpqDPj4QI7Jv8_S41GQ?e=aQ2Bb8', 46, '2025-10-06 08:50:48'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Page Homework chart -students-A2-kirkuk', 'Homework chart design for Kirkuk students', 'medium', 'Design', 'Kirkuk', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:b:/s/MarketingTEAM/EW-Nzd4DJ45OtK0Bxe9B8VYB4uCWpqDPj4QI7Jv8_S41GQ?e=NH2W87', 47, '2025-10-06 08:51:06'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Page quize -students-A2-kirkuk', 'Quiz page design for Kirkuk students', 'medium', 'Design', 'Kirkuk', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:b:/s/MarketingTEAM/EYmFxU1t0xRHjn40bu2p-3wB0WxYM62I6MrhPlaITTw4g?e=0HXTPl', 48, '2025-10-06 08:52:09'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Page quize -students-A2-baghdad', 'Quiz page design for Baghdad students', 'medium', 'Design', 'Baghdad', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:b:/s/MarketingTEAM/EVkYWP133OlIhq06z_XGchQBSZ32aRqIOK6UrERP68XPEg?e=XDYuXV', 49, '2025-10-06 08:52:32');

-- Continue inserting more completed tasks
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'post English open New Classes-basra', 'English new classes opening post for Basra', 'medium', 'Design', 'Basra', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EkNk8J8fDddApNFkQqLV4q0BARTMf_Px4WipxfQYAFlM9Q?e=oF4UIy', 50, '2025-10-06 08:53:41'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'post arabic open New Classes-basra', 'Arabic new classes opening post for Basra', 'medium', 'Design', 'Basra', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EkNk8J8fDddApNFkQqLV4q0BARTMf_Px4WipxfQYAFlM9Q?e=oF4UIy', 51, '2025-10-06 08:54:09'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'page home work chart_baghdad', 'Homework chart page for Baghdad', 'medium', 'Update/Technical', 'Baghdad', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EvS43p4nCMFPjK7_e8ZdHxgBCubrvapDgQVGIb49sqIeuw?e=CIj0BQ', 52, '2025-10-06 08:54:57'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'poster New one minute talk', 'One minute talk poster design', 'medium', 'Design', 'Stirling Schools', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/EduPortal/EpnBgF4imTNBtPofTQw7FxoB0e8Ms_ECIbDs03q6gEftbw?e=TidqU7', 53, '2025-10-06 11:39:00'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'HMR VIDEO AILE', 'HMR family video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1460351601795546', 54, '2025-10-07 12:56:24'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'salahadddin high school', 'Salahaddin high school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=790634653598042&set=pcb.790635216931319', 55, '2025-10-07 13:00:48'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'usısı teacher days', 'USIS teacher days coverage', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1248617627309337', 56, '2025-10-07 13:03:01'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'usısı after school', 'USIS after school activities', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=791341936860647&set=pcb.791342183527289', 57, '2025-10-07 13:05:52'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'US TANITIM FILMI', 'US promotional film', 'high', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/EduPortal/EnUJr3A_miBBsyASBBH5gAwBAfhOSc_G-sM9k761-PqZLw?e=q8Sivc', 58, '2025-10-07 13:10:34'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'us girls higih school', 'US girls high school coverage', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=791379540190220&set=pcb.791379703523537', 59, '2025-10-07 13:14:19');

-- Insert task that is in progress
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'In Progress' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'RAISE TANITIM VIDEO FOTO', 'Rise promotional video and photo content', 'high', 'Video/Photo', 'Erbil', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 0, '2025-10-20 05:51:58');

-- Insert tasks in queue/backlog
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Backlog' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'bagdad erkek okul video montaj', 'Baghdad boys school video editing', 'medium', 'Video/Photo', 'Baghdad', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 0, '2025-10-05 06:38:34'),
((SELECT id FROM columns WHERE name = 'Backlog' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Stirling Schools Guid Handbook', 'Stirling Schools guidance handbook design', 'medium', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 1, '2025-10-13 08:32:53'),
((SELECT id FROM columns WHERE name = 'Backlog' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'USIS', 'USIS video content creation', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 2, '2025-10-13 08:54:57'),
((SELECT id FROM columns WHERE name = 'Backlog' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day November', 'International special day for November', 'low', 'Design', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 3, '2025-10-19 07:35:13'),
((SELECT id FROM columns WHERE name = 'Backlog' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'BASRA REELS VIDEO OUTRO UPDATE', 'Basra reels video outro update', 'medium', 'Video/Photo', 'Basra', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 4, '2025-10-20 05:53:01');
