
-- Continue inserting more completed tasks from the Excel data
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'us girls secondary school', 'US girls secondary school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=791515426843298&set=pcb.791515950176579', 60, '2025-10-08 05:15:09'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik gulan math video', 'Ishik Gulan math video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1344074927327114', 61, '2025-10-08 05:18:39'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik gulan kindergarten', 'Ishik Gulan kindergarten video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1216082350551974&set=pcb.1216083827218493', 62, '2025-10-08 05:20:36'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Nilufer girls high school', 'Nilufer girls high school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1216171347209741&set=pcb.1216171587209717', 63, '2025-10-08 05:24:37'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ronaki international school- afeter schoool', 'Ronaki international school after school activities', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1216265530533656&set=pcb.1216265657200310', 64, '2025-10-08 05:27:37'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Soran intrenational school', 'Soran international school video content', 'medium', 'Video/Photo', 'Slemani', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/746057385155622', 65, '2025-10-08 05:30:12'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Nilufer school', 'Nilufer school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1216988387128037&set=pcb.1216988657128010', 66, '2025-10-08 05:32:24'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İshik Gulan İnternational shclool', 'Ishik Gulan International school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1217074893786053&set=pcb.1217075320452677', 67, '2025-10-08 05:35:05'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İshik gulan primary school', 'Ishik gulan primary school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1217736803719862&set=pcb.1217737460386463', 68, '2025-10-08 07:10:32'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'kral gunu video secmek ve erken kayid kaldirmak', 'King Day video selection and early registration removal', 'high', 'Video/Photo', 'Stirling Schools', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/EoEybU7nBulIuMRxudiwlWoBDndR67ZfmWRKb8KWu5rh1Q?e=0uDFSj', 69, '2025-10-08 10:09:36');

-- Insert more design tasks
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'STIRLING SCHOOLS IN 18 VIDEO REEL', 'Stirling Schools 18 video reel compilation', 'high', 'Video/Photo', 'Stirling Schools', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1223681876458688&set=pcb.1223682776458598', 70, '2025-10-08 12:38:22'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Rise Car Glass Sticker', 'Rise car glass sticker design', 'medium', 'Design', 'Erbil', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EozX4mUOxKFCsFFAVONzSUABWic_RtWeEClrG549ie21yA?e=QcQwUh', 71, '2025-10-08 13:43:29'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'olympiads handbook 3 edit amd redesign', 'Olympiads handbook 3 edit and redesign', 'medium', 'Design', 'Erbil', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EukRhoeseMpCjJ0nIYqfd0UB7yE_GP2hzfU2T-K7tsoT9w?e=epL8rE', 72, '2025-10-08 13:46:25'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Baghdad Letterhead a4', 'Baghdad letterhead A4 design', 'medium', 'Design', 'Baghdad', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Etokj6IksydAnPmOm_Nr80ABurcJMuzUkxs6GYoiNfsf8Q?e=Pf8dEE', 73, '2025-10-08 13:47:59'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Baghdad Uni Placement Abroad', 'Baghdad university placement abroad design', 'medium', 'Design', 'Baghdad', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EkRx-mZe8JZKgWFK4rvgmkkB5mz8L2OMUFRQD4-znT56qQ?e=o3o9oR', 74, '2025-10-08 13:48:34'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'USC Printing Materials', 'USC printing materials design', 'medium', 'Design', 'Erbil', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EnYs6ndix3lBgv4Pgl2ziDsB6s71v0NNsuN5rATZoknG0w?e=vpcNw1', 75, '2025-10-08 13:48:58'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Stirling Schools', 'Stirling Schools general design materials', 'medium', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EuJO2q6UNZRPpM_lnCwQbjMBUibN_jG55FLIcd0FASFhEA?e=0VxDgr', 76, '2025-10-08 13:50:09'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Erbil', 'Erbil design materials', 'medium', 'Design', 'Erbil', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EuJO2q6UNZRPpM_lnCwQbjMBUibN_jG55FLIcd0FASFhEA?e=0VxDgr', 77, '2025-10-08 13:50:43'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik boys highi school', 'Ishik boys high school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1218706616956214&set=pcb.1218709063622636', 78, '2025-10-09 07:35:52'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'After-school activity (Slemani International Primary School - 1)', 'After-school activity at Slemani International Primary School', 'medium', 'Video/Photo', 'Slemani', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1233777642120126', 79, '2025-10-09 07:37:41');

-- Continue with more tasks from October
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'usis travel chaviland', 'USIS travel to Chaviland video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=793038790024295&set=pcb.793039073357600', 80, '2025-10-09 07:40:00'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'usıs sciecnce', 'USIS science activity video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/24914901058141543', 81, '2025-10-09 07:41:56'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'acadimic calendar', 'Academic calendar updates', 'high', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/educationoffice/ErYt4tl1AxFAgqaGQvXXjRYBOxJZ7bo3wa516Xxqbee32w?e=OqRDR0', 82, '2025-10-09 09:45:29'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İshik boys high school', 'Ishik boys high school video coverage', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1218706616956214&set=pcb.1218709063622636', 83, '2025-10-12 07:30:18'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İshik gulan Teakvando', 'Ishik Gulan Taekwondo video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1218845250275684&set=pcb.1218845503608992', 84, '2025-10-12 07:33:07'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Nilufer girls higih school', 'Nilufer girls high school video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=1218883456938530&set=pcb.1218884570271752', 85, '2025-10-12 07:36:42'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Rise School', 'Rise School video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=1219017653591777&set=a.447946767365540', 86, '2025-10-12 07:38:57'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'RISE', 'Rise school additional video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1219079773585565&set=pcb.1219080296918846', 87, '2025-10-12 07:41:22'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik gulan international school', 'Ishik Gulan international school video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1219705023523040&set=pcb.1219705336856342', 88, '2025-10-12 07:43:37'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Nilufer Girls High School', 'Nilufer Girls High School video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1219842230175986&set=pcb.1219842443509298', 89, '2025-10-12 07:45:46');

-- Add more October tasks continuing the sequence
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ishik gulan international school', 'Ishik Gulan international school reel', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1999514307449667', 90, '2025-10-12 07:54:04'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İSHİK boys high school', 'Ishik boys high school reel content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1086616913311334', 91, '2025-10-12 07:55:39'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İshik ronaki international school', 'Ishik Ronaki international school video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1221667863326756&set=pcb.1221668319993377', 92, '2025-10-12 07:57:26'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'RISE', 'Rise school additional content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=1221783333315209&set=pcb.1221784086648467', 93, '2025-10-12 07:59:04'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Usıs', 'USIS video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/24914901058141543', 94, '2025-10-12 08:02:19'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'USIS', 'USIS additional video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=793038790024295&set=pcb.793039073357600', 95, '2025-10-12 08:04:32'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Suaymaniyah Primary 1', 'Sulaymaniyah Primary 1 video content', 'medium', 'Video/Photo', 'Slemani', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1507421820573360', 96, '2025-10-12 08:06:52'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Slemani Girls High School', 'Slemani Girls High School video content', 'medium', 'Video/Photo', 'Slemani', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1358566882451575', 97, '2025-10-12 08:10:45'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Slemani International Girls Secondary School', 'Slemani International Girls Secondary School', 'medium', 'Video/Photo', 'Slemani', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=795784013083106&set=pcb.795784723083035', 98, '2025-10-12 08:15:22'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ACADEMIC CALENDAR', 'Academic calendar management system', 'high', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/educationoffice/ErYt4tl1AxFAgqaGQvXXjRYBOxJZ7bo3wa516Xxqbee32w?e=OqRDR0', 99, '2025-10-12 09:29:45');
