
-- Insert the final batch of completed tasks from the Excel data
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ACADEMIC CALENDAR (Additional)', 'Additional academic calendar updates', 'high', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/educationoffice/EioloYzM23NEjrYtWfEHYLIBX87I1tb0rOeucNUDjgg_Og?e=sLpAf8', 100, '2025-10-12 09:32:49'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ACADEMIC CALENDAR Final', 'Final academic calendar version', 'high', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/educationoffice/EioloYzM23NEjrYtWfEHYLIBX87I1tb0rOeucNUDjgg_Og?e=sLpAf8', 101, '2025-10-13 06:36:17'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'National & International Olympiads Poster', 'National and International Olympiads poster design', 'high', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Egiqi9gEWLpFqLW9r08TPb4BaOtpvYhiw_sOcNxyrx8EPg?e=ed7KKr', 102, '2025-10-13 08:14:00'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Certificate of Participation', 'Certificate of participation design', 'medium', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ek0YIiRN5nhCve-QiH03NT0B2fjal4ecuKV3vr4HqzEC5A?e=BYjY7h', 103, '2025-10-13 08:16:38'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Wezary Study Planner', 'Wezary study planner design', 'medium', 'Design', 'Stirling Schools', 'Samar', 'samar.ahmed@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/ElD_Q2E4IVpOqRXnK5Phkj4B8n9ePAQ1h5yReaaRKN9c8A?e=K7r7ic', 104, '2025-10-13 08:18:42'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Golden Star Baghdad Ishik Schools-2025-56-Secondary', 'Golden Star Baghdad Ishik Schools secondary design', 'high', 'Design', 'Baghdad', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/ErHOo_n7GopEiZ001ifQYEEBRpfS04DDUYZXSjkpWsfRUw?e=MqlnyV', 105, '2025-10-13 08:25:19'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik Gulan International School Video', 'Ishik Gulan International School video content', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/842093648342071', 106, '2025-10-13 08:31:12'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Post-Japan-Hiking', 'Post-Japan hiking activity design', 'medium', 'Design', 'Stirling Schools', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EhbK0T2jPaVMgn5tjmUiQcwBga_7c8faQDwPyec-jA37vQ?e=hhatwU', 107, '2025-10-13 08:32:56'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'post-japan-Aloha Spirit week', 'Post-Japan Aloha Spirit week design', 'medium', 'Design', 'Stirling Schools', 'Farhad', 'farhad.faruq@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/EhbK0T2jPaVMgn5tjmUiQcwBga_7c8faQDwPyec-jA37vQ?e=hhatwU', 108, '2025-10-13 08:33:50'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik International Boys Secondary School', 'Ishik International Boys Secondary School video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1222692073224335&set=pcb.1222692533224289', 109, '2025-10-13 08:35:33');

-- Add the most recent October 2025 tasks
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day September', 'International special day content for September', 'medium', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ep7HD3GtOx9LjNbOsUhTEP0BU-GBTU6zd2-BtPO92gL8tg?e=tlTg8B', 110, '2025-10-19 07:25:02'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day October', 'International special day content for October', 'medium', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ep7HD3GtOx9LjNbOsUhTEP0BU-GBTU6zd2-BtPO92gL8tg?e=tlTg8B', 111, '2025-10-19 07:28:07'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day November Design', 'International special day November design', 'medium', 'Design', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ep7HD3GtOx9LjNbOsUhTEP0BU-GBTU6zd2-BtPO92gL8tg?e=tlTg8B', 112, '2025-10-19 07:36:05'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day DECEMBER', 'International special day content for December', 'medium', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ep7HD3GtOx9LjNbOsUhTEP0BU-GBTU6zd2-BtPO92gL8tg?e=tlTg8B', 113, '2025-10-19 07:38:20'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day January', 'International special day content for January', 'medium', 'Update/Technical', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ep7HD3GtOx9LjNbOsUhTEP0BU-GBTU6zd2-BtPO92gL8tg?e=tlTg8B', 114, '2025-10-19 07:40:05'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'international special day May', 'International special day content for May', 'medium', 'Design', 'Stirling Schools', 'Ibrahim', 'ibrahimyousif.0098@gmail.com', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingTEAM/Ep7HD3GtOx9LjNbOsUhTEP0BU-GBTU6zd2-BtPO92gL8tg?e=tlTg8B', 115, '2025-10-19 07:53:46'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'İshik Gulan İnternational Kindargertan', 'Ishik Gulan International Kindergarten video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1222892056537670&set=pcb.1222892429870966', 116, '2025-10-19 08:59:25'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik International Boys Secondary School final', 'Ishik International Boys Secondary School final video', 'high', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1223681876458688&set=pcb.1223682776458598', 117, '2025-10-19 09:04:24'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'ERBIL RAISE OKUL TANITIM VIDEO FOTO CEKIM', 'Erbil Rise school promotional video and photo shooting', 'high', 'Video/Photo', 'Erbil', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/EuZqzB7rFl9MqlBRQUBaKLUBPgA_u8G9GPuA7NROIZUAXw?e=ikqqo7', 118, '2025-10-20 05:40:42'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'GULAN ILK OKUL KAMP OKUL ICINDE FOTO VIDEO', 'Gulan primary school camp inside school photo video', 'medium', 'Video/Photo', 'Erbil', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/Ep9jvOXmb6tBgHziHj3nxKsBlNfYoQG56wZCd9GjaFi42A?e=pxQjgA', 119, '2025-10-20 05:41:53');

-- Add final tasks to complete the migration
INSERT INTO tasks (column_id, title, description, priority, task_type, city, requester_name, requester_email, project_link, position, created_at) VALUES
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'BAGDAD BASRA KRAL GUNU VIDEO MOTAJ', 'Baghdad Basra King Day video editing', 'medium', 'Video/Photo', 'Baghdad', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/Emdb3_TldeBNoaB2vvx0_soBPUSUiEof-_1HsrdlG9Iiig?e=IUuG76', 120, '2025-10-20 05:43:25'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'GULAN ILK OKUL SON BAHAR KAMP VIDEO FOTO', 'Gulan primary school autumn camp final video photo', 'medium', 'Video/Photo', 'Erbil', 'Ahmed', 'ahmed.ekrem@stirlingschools.co.uk', 'https://stirlingschools.sharepoint.com/:f:/s/MarketingArchive/Ep9jvOXmb6tBgHziHj3nxKsBlNfYoQG56wZCd9GjaFi42A?e=WBocKh', 121, '2025-10-20 05:50:02'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik Gulan International School Recent', 'Ishik Gulan International School recent video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1228205756006300&set=pcb.1228205962672946', 122, '2025-10-20 09:18:45'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik Ronaki International School Recent', 'Ishik Ronaki International School recent video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo/?fbid=1228406182652924&set=pcb.1228406285986247', 123, '2025-10-20 09:20:39'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik Ronaki International School Final', 'Ishik Ronaki International School final video', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/photo?fbid=1228835272610015&set=pcb.1228835392610003', 124, '2025-10-20 09:22:58'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik Gulan International School Latest', 'Ishik Gulan International School latest reel', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/3684068758568807', 125, '2025-10-20 09:24:45'),
((SELECT id FROM columns WHERE name = 'Done' AND board_id = (SELECT id FROM boards WHERE name = 'Stirling Schools Marketing Task Board')), 'Ishik Gulan International Primary School Latest', 'Ishik Gulan International Primary School latest reel', 'medium', 'Video/Photo', 'Erbil', 'Erhan', 'erhan.bedri@stirlingschools.co.uk', 'https://www.facebook.com/reel/1810482873162615', 126, '2025-10-20 09:27:18');
